### ISSUE TITLE
JOSS review: questions on 00-mwe.py

### ISSUE THREAD

**Issue by erexer** [NERDSITU/superblockify#88]
This is for the [JOSS review](https://github.com/openjournals/joss-reviews/issues/6798).

I have a couple questions about the minimum working example. I'm running `00-mwe.py` after installing using micromamba and pip. I'm on a Mac v14.5, python v3.12.3.
1. Is "residential" referring to number of residential streets? If so, why does it have non-whole numbers? The y-axis should specify which "length" unit it's referring to. 
<img width="632" alt="image" src="https://github.com/NERDSITU/superblockify/assets/13180883/439acf16-b336-48a7-bd25-909b9fe94a31">

2. in the x-axis label on this figure (Distribution of shortest path lengths on full graph) and for the "Distribution of shortest path distances for the partitioning" figure, what does "[s]" mean? Do the "Coordinates of nodes" graph x- and y-axis have units (lat/lon)?
<img width="982" alt="image" src="https://github.com/NERDSITU/superblockify/assets/13180883/2f119faf-9f18-4c6f-8245-bbf58a821ddf">

3. I'm having an issue where the figures after "Distribution of shortest path distances for the partitioning" don't load if I wait 50 seconds or longer before I close the python window for "Distribution of shortest path distances for the partitioning", it pops up three python windows labeled "Figure 1", "Figure 2", and "Figure 3" which are all completely blank. When I hover over the window, it shows the spinny wheel of death and I have to force quit python. When I wait less than 50 seconds before closing "Distribution of shortest path distances for the partitioning", it pops up Figure 2, 3, and 4 fine and I can see the charts. 

4. What is "Part." short for? Not sure abbreviating is necessary. Is "(s)" seconds? 
<img width="865" alt="image" src="https://github.com/NERDSITU/superblockify/assets/13180883/e44498ab-0c38-48ff-ba31-7305d343a349">

5. I assume these are separate color bars since the left one says that dark green is 1 and the right color bar says that dark green is 400. Can you make it clear which graphs they apply to? If they aren't separate color bars, can you explain the scale? Again, what does "(s)" stand for? 
<img width="935" alt="image" src="https://github.com/NERDSITU/superblockify/assets/13180883/99ea5109-9220-4fe9-93b5-fd770cacaf01">

6. Is there a glossary of terms somewhere? 

If any of these are explained in the documentation, I would love to be pointed towards it! I may have missed it :)

**Comment by cbueth** [comment]
Thank you very much for trying out our minimum working example and the notes.

Sorry for the late response. For some reasons issue email notifications were deactivated, but they are active now on our side.

From your notes we have implemented changes in ee6f76fe2b884f197af4c6778c97a93a320021ed and faf9c1febbe04ecc6573483b8d0c35ac87441a4b. With PR #89 the changes will be merged.

- (3.) We have generally changed when the plots are being shown. Now all plots will be shown at the end of the run() method at once. We were not able to reproduce the behavior you described, but this should fix it and is more aligned with the best practice. Thank you for this valuable hint.
- (1.) We have removed the "Component size of"-plot as it is too similar to the size rank plot, now called "Superblock size rank for".  The plot before was like the size rank plot, comparing the distribution of street length sum in each Superblock, but was unordered in contrast to the size rank plot.
![Figure_2](https://github.com/user-attachments/assets/ab907ad9-96df-439e-8424-a57ed49fd64d)
- (2.) For the path length distribution plots we improved the labeling. Shown are the projected coordinates in meters for Lat/Lon.
![Figure_4](https://github.com/user-attachments/assets/8466b04c-414c-4300-9425-cd390deb3dec)
- (4.) "Part." is partition abbreviated. We call areas partitions internally that later are superblocks, but sometimes partitions need to fuse to one superblock out of topological reasons. Finally, we renamed the lables for all plots this to say superblock(s).
- (5.) The "pairwise relative difference"-plot fuses the "Distance matrix" and "Relative difference" plots. In the case of having more than two distance metrics one would be able to compare each distance metric pairwise in one plot. We now decided only to show the two latter ones, and only if the user activated debug logging, as the insight from these plots is not seen as big. Also, the labeling on these two plots is clearer, e.g. having only one colorbar.
- (2.,4.,5.) Yes, we use SI units, so "s" stands for seconds and "m" for meters, the unit always in brackets. This means that distance must be understood as travel time when "(s)" is given. This is due to the feature that one can change the unit distance is measured.
- (6.) There is no central glossary of terms until now, you did not miss it. The documentation pages, including Usage and Reference pages should introduce the package's background.

Please, let us know if you have any questions related :clap:

**Comment by erexer** [comment]
Great! I'm running `00-mwe.py` on the `88-joss-review-questions-on-00-mwepy` branch, but I'm still seeing a "Component size of Scheveningen_test" plot, was that supposed to be removed in (1.)?

**Comment by cbueth** [comment]
For these changes to appear you need to install the package in editable mode from the repository, different than the user documentation says. Have you done this?

You can create a separate environment like so (from the `CONTRIBUTING.md`):

```bash
conda create -n sb_env_dev -c conda-forge python=3.12 -f environment-dev.yml
conda activate sb_env_dev
pip install --no-build-isolation --no-deps -e .
```

**Comment by erexer** [comment]
Thanks for making these changes and for the editable installation instructions! It's running well on my end. 

> (2.,4.,5.) This means that distance must be understood as travel time when "(s)" is given. 
Gotcha, in that case I'd recommend changing the label on the graph to "Travel time (s)" since using seconds for distance is unintuitive. 

> (2.) For the path length distribution plots we improved the labeling. Shown are the projected coordinates in meters for Lat/Lon.
I've never seen lat/lon in meters before, how does that translate from degrees?

**Comment by cbueth** [comment]
Great to hear!

> Gotcha, in that case I'd recommend changing the label on the graph to "Travel time (s)" since using seconds for distance is unintuitive.

We'll see on how to elegantly implement that change, it's definitely more concise that way! 

> I've never seen lat/lon in meters before, how does that translate from degrees?

As these are projected coordinates, projected to the current CRS of the place, these are in meters. This way we can use Euclidean distances. These are commonly called y and x, but somewhat correlate to latitude and longitude. I'd change it to y and x.

We'll make these changes if you find the choices reasonable and afterwards push a new release candidate if that would close this issue.

**Comment by erexer** [comment]
Yep, making those changes would close this issue.

**Comment by cbueth** [comment]
We have just merged the changes after a successful CI and published the release candidate [`1.0.0rc10` on PyPI](https://pypi.org/project/superblockify/) including the changes.
Thank you again for reviewing and testing our package!
